/**
 * storage open api
 * storage open api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* 获取上传凭证
*/
export class CredentialsReq {
    /**
    * 上传渠道，腾讯云：qcloud、阿里云：aliyun、七牛：qiniu
    */
    'channel': string;
    /**
    * 计算凭证参数，具体数据结构与上传渠道对应
    */
    'params': object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string"
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return CredentialsReq.attributeTypeMap;
    }
}

