/**
 * storage open api
 * storage open api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* 腾讯云上传凭证数据
*/
export class QCloudCredentialsData {
    /**
    * 请求时需要用的 token 字符串，最终请求 COS API 时，需要放在 Header 的 x-cos-security-token 字段
    */
    'sessionToken': string;
    /**
    * 临时密钥 Id，可用于计算签名
    */
    'tmpSecretId': string;
    /**
    * 临时密钥 Key，可用于计算签名
    */
    'tmpSecretKey': string;
    /**
    * 密钥的起始时间戳（毫秒）
    */
    'startTime': number;
    /**
    * 密钥的失效时间戳（毫秒）
    */
    'expiredTime': number;
    /**
    * 请求ID
    */
    'requestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sessionToken",
            "baseName": "sessionToken",
            "type": "string"
        },
        {
            "name": "tmpSecretId",
            "baseName": "tmpSecretId",
            "type": "string"
        },
        {
            "name": "tmpSecretKey",
            "baseName": "tmpSecretKey",
            "type": "string"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "number"
        },
        {
            "name": "expiredTime",
            "baseName": "expiredTime",
            "type": "number"
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return QCloudCredentialsData.attributeTypeMap;
    }
}

