/**
 * storage open api
 * storage open api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* 腾讯云计算上传凭证参数
*/
export class QCloudCredentialsParams {
    /**
    * 存储桶所在区域，如：ap-guangzhou
    */
    'region': string;
    /**
    * 存储桶名称
    */
    'bucket': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "bucket",
            "baseName": "bucket",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return QCloudCredentialsParams.attributeTypeMap;
    }
}

